### ISSUE TITLE
ConsumerFile Assumptions

### ISSUE THREAD

**Issue by JamesHabben** [Invoke-IR/Uproot#16]
Using the Add-WmiEventConsumer, the -ConsumerFile parameter assumes that there is a folder in the current path, and appends ".ps1" on the end of the value. If you use the [tab] autocomplete of powershell, in order to find the file, then you cause an error because it adds the extra string data.

**Comment by jaredcatkinson** [comment]
I added a dynamic parameter to both Add-WmiEventFilter and Add-WmiEventConsumer.  Now you can use "Add-WmiEventConsumer -ConsumerFile [tab]" and it will begin tabbing through Consumer files in the Consumers directory.
