### ISSUE TITLE
Pipe Get-WmiEventSubscription to Remove-WmiEventSubscription

### ISSUE THREAD

**Issue by JamesHabben** [Invoke-IR/Uproot#20]
This command doesn't do anything to remove the subscriptions.

Get-WmiEventSubscription | Remove-WmiEventSubscription

**Comment by JamesHabben** [comment]
Get-WmiEventFilter | Remove-WmiEventFilter

doesn't appear to work either

**Comment by JamesHabben** [comment]
should the -name be assumed if its not supplied?

this creates error:
Remove-WmiEventFilter ProcessCreation

this works:
Remove-WmiEventFilter -name ProcessCreation

**Comment by jaredcatkinson** [comment]
Just fixed all of these issues in my latest commit!  Also added a -Force parameter to Remove-WmiEventSubscription that will remove the filter and consumer in addition to the binding/subscription
